#!/usr/bin/env python3
"""Generate a conservative katakana loanword-origin table from JMdict JSON.

The input is a pinned jmdict-simplified English JSON release. Only complete,
non-wasei source records with an explicit source word are eligible. Surfaces
with conflicting source records are omitted instead of guessed.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import unicodedata
from collections import defaultdict
from pathlib import Path


CANONICAL_LANGUAGES = {
    "eng": "eng",
    "ger": "ger",
    "fre": "fre",
    "spa": "spa",
    "ita": "ita",
    "dut": "dut",
    "por": "por",
    "rus": "rus",
    "chi": "chi",
    "kor": "kor",
    "lat": "lat",
    "gre": "gre",
    "grc": "gre",
    "vie": "vie",
    "san": "san",
    "tur": "tur",
    "tha": "tha",
    "hin": "hin",
    "fin": "fin",
    "swe": "swe",
    "mon": "mon",
    "hun": "hun",
    "may": "may",
    "dan": "dan",
    "nor": "nor",
    "cze": "cze",
}
WHITESPACE = re.compile(r"\s+")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Extract unambiguous katakana loanword origins from JMdict JSON."
    )
    parser.add_argument("--input", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--source-version", required=True)
    parser.add_argument("--source-url", required=True)
    parser.add_argument("--source-sha256", required=True)
    return parser.parse_args()


def is_katakana_surface(value: str) -> bool:
    characters = list(value)
    if len(characters) < 2:
        return False
    if not any("ァ" <= character <= "ヺ" for character in characters):
        return False
    return all(
        "ァ" <= character <= "ヺ" or character in {"ー", "・", "ヽ", "ヾ"}
        for character in characters
    )


def normalize_origin(value: object) -> str:
    if not isinstance(value, str):
        return ""
    normalized = WHITESPACE.sub(" ", unicodedata.normalize("NFC", value).strip())
    if not normalized or len(normalized) > 80:
        return ""
    if any(unicodedata.category(character) in {"Cc", "Cs"} for character in normalized):
        return ""
    return normalized


def extract(data: dict) -> tuple[list[tuple[str, str, str]], int]:
    candidates: dict[str, set[tuple[str, str]]] = defaultdict(set)

    for word in data.get("words", []):
        forms = {
            item.get("text", "")
            for item in word.get("kana", [])
            if is_katakana_surface(item.get("text", ""))
        }
        if not forms:
            continue

        for sense in word.get("sense", []):
            sources: set[tuple[str, str]] = set()
            for source in sense.get("languageSource", []):
                language = CANONICAL_LANGUAGES.get(source.get("lang"))
                origin = normalize_origin(source.get("text"))
                if (
                    language
                    and origin
                    and source.get("full") is True
                    and source.get("wasei") is False
                ):
                    sources.add((language, origin))
            if not sources:
                continue

            restrictions = sense.get("appliesToKana", ["*"])
            applicable_forms = forms if "*" in restrictions else forms.intersection(restrictions)
            for surface in applicable_forms:
                candidates[surface].update(sources)

    entries = [
        (surface, *next(iter(sources)))
        for surface, sources in candidates.items()
        if len(sources) == 1
    ]
    entries.sort(key=lambda item: item[0])
    ambiguous_count = sum(len(sources) > 1 for sources in candidates.values())
    return entries, ambiguous_count


def render(
    entries: list[tuple[str, str, str]],
    *,
    dictionary_date: str,
    source_version: str,
    source_url: str,
    source_sha256: str,
    ambiguous_count: int,
) -> str:
    metadata = {
        "dictionaryDate": dictionary_date,
        "sourceVersion": source_version,
        "sourceUrl": source_url,
        "sourceSha256": source_sha256.upper(),
        "entryCount": len(entries),
        "ambiguousSurfacesOmitted": ambiguous_count,
        "license": "CC BY-SA 4.0 / EDRDG General Dictionary Licence",
    }
    lines = [
        "// Generated by scripts/generate-loanword-origins.py; do not edit by hand.",
        "// Derived from JMdict data. See THIRD_PARTY_NOTICES.md and third_party_licenses/jmdict/.",
        f"export const JMDICT_LOANWORD_ORIGIN_METADATA = Object.freeze({json.dumps(metadata, ensure_ascii=False, separators=(',', ':'))});",
        "",
        "export const JMDICT_LOANWORD_ORIGINS = Object.freeze([",
    ]
    lines.extend(
        f"  Object.freeze({json.dumps(entry, ensure_ascii=False, separators=(',', ':'))}),"
        for entry in entries
    )
    lines.extend(["]);", ""])
    return "\n".join(lines).replace("\u2028", "\\u2028").replace("\u2029", "\\u2029")


def main() -> None:
    args = parse_args()
    source_bytes = args.input.read_bytes()
    actual_sha256 = hashlib.sha256(source_bytes).hexdigest().upper()
    expected_sha256 = args.source_sha256.upper()
    if actual_sha256 != expected_sha256:
        raise SystemExit(
            f"JMdict JSON SHA-256 mismatch: expected {expected_sha256}, got {actual_sha256}"
        )

    data = json.loads(source_bytes)
    entries, ambiguous_count = extract(data)
    if len(entries) < 500:
        raise SystemExit(f"Unexpectedly small generated dictionary: {len(entries)} entries")

    output = render(
        entries,
        dictionary_date=str(data.get("dictDate", "")),
        source_version=args.source_version,
        source_url=args.source_url,
        source_sha256=actual_sha256,
        ambiguous_count=ambiguous_count,
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(output, encoding="utf-8", newline="\n")
    print(
        f"Generated {len(entries)} unambiguous origins at {args.output} "
        f"({ambiguous_count} ambiguous surfaces omitted)."
    )


if __name__ == "__main__":
    main()
